# Generated by Django 4.2.5 on 2023-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inter_university_event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inter_university_event",
            name="excel_sheet_link",
            field=models.URLField(
                blank=True, db_index=True, max_length=512, unique=True
            ),
        ),
    ]
