# Generated by Django 4.2.5 on 2023-10-16 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inter_university_event", "0002_inter_university_event_excel_sheet_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Inter_University_Event",
        ),
    ]
