# Generated by Django 4.2.5 on 2023-10-16 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inter_university_event", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="team",
        ),
        migrations.RemoveField(
            model_name="team",
            name="event",
        ),
        migrations.DeleteModel(
            name="Inter_University_Event",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
