# Generated by Django 3.2.21 on 2023-10-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter_university_event', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_key',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
