# Generated by Django 4.2.5 on 2023-09-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intra_university_event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intra_university_event",
            name="google_form_link",
            field=models.URLField(
                blank=True, db_index=True, max_length=512, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="intra_university_event",
            name="time",
            field=models.DateTimeField(blank=True),
        ),
    ]
