# Generated by Django 4.2.5 on 2023-09-24 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intra_university_event", "0003_intra_university_event_excel_sheet_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intra_university_event",
            name="excel_sheet_link",
        ),
    ]
