# Generated by Django 4.2.5 on 2023-09-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "intra_university_event",
            "0004_remove_intra_university_event_excel_sheet_link",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="intra_university_event",
            name="excel_sheet_link",
            field=models.URLField(
                blank=True, db_index=True, max_length=512, unique=True
            ),
        ),
    ]
