# Generated by Django 4.2.5 on 2023-10-12 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intra_university_event", "0006_intra_university_event_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intra_university_event",
            name="image",
        ),
    ]
