# Generated by Django 4.2.5 on 2023-10-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intra_university_event", "0008_intra_university_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intra_university_event",
            name="excel_sheet_link",
            field=models.URLField(
                blank=True, db_index=True, max_length=512, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="intra_university_event",
            name="google_form_link",
            field=models.URLField(
                blank=True, db_index=True, max_length=512, null=True, unique=True
            ),
        ),
    ]
