# Generated by Django 4.2.5 on 2023-10-16 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "intra_university_event",
            "0009_alter_intra_university_event_excel_sheet_link_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Intra_University_Event",
        ),
    ]
