# Generated by Django 4.2.5 on 2023-10-16 16:58

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("intra_university_event", "0010_delete_intra_university_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intra_University_Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("time", models.DateTimeField(blank=True)),
                (
                    "google_form_link",
                    models.URLField(
                        blank=True,
                        db_index=True,
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "excel_sheet_link",
                    models.URLField(
                        blank=True,
                        db_index=True,
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="intra_event_images"
                    ),
                ),
                ("content", mdeditor.fields.MDTextField()),
            ],
        ),
    ]
